name: "Build example collection"
description: "Wrapper action for building specific example"
runs:
  using: "composite"
  steps:
    - name: Build example
      shell: bash
      run: strava-collections -i 'examples/bavarian-alps-traverse.yml'
      env:
        STRAVA_CACHE_DIR: temporary-strava-activities
