name: "Build all collections"
description: "Wrapper action for building all collections"
runs:
  using: "composite"
  steps:
    - name: Loop over all collections and build
      run: for file in examples/*.yml; do echo $file; strava-collections -i $file; done
