name: Build Strava Collections

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
  STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
  STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection:
          - name: bavarian-alps
            ids: "12284003055F 12231765525 11603714471F 11487681160 11492585278 9020068072 11518973205 9327605554F 9586696097 9961995244"
            title: "Bavarian alps traverse"
          - name: singapore-kl
            ids: "836894407 838026669 838748059 840195182"
            title: "Singapore to Kuala Lumpur"
          - name: ibiza
            ids: "10184212131 10188508424 10201453185 10209283997 10210461413 10215286376 10220935820 10223047971 10232455929 10239392263 10240530649 10244023732"
            title: "Ibiza sailing trip"
          # Add as many as you want...

    steps:
      - uses: actions/checkout@v3

      - name: Restore Strava cache
        uses: actions/cache/restore@v3
        with:
          path: cache/
          key: strava-cache-v1
          restore-keys: |
            strava-cache-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          pip install --upgrade pip
          pip install ".[dev,docs]"

      - name: Build Strava collection
        run: |
          strava-collections ${{ matrix.collection.ids }} \
            -o docs/source/ \
            -c "${{ matrix.collection.title }}"

      - name: Save Strava cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: cache/
          key: strava-cache-v1

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Build docs
        run: |
          cd docs
          make clean
          make html
          cd ..
          ls docs/build/html/index.html
