name: Tests

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

env:
  STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
  STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
  STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust as needed

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install project
        run: |
          pip install --upgrade pip
          pip install ".[dev]"

      - name: Check installation
        run: |
          strava-collections -h
          strava-collections 7575170664

      - name: Run tests
        run: |
          pytest .

      - name: Test tutorials
        run: |
          jupyter nbconvert --to notebook --execute tutorials/*.ipynb --output-dir=/tmp --ExecutePreprocessor.timeout=300

      - name: Test docs build
        run: |
          pip install ".[docs]"
          mkdir -p docs/source/_static/plots/bavarian-alps
          strava-collections 12284003055F 12231765525F 11603714471F 11487681160 11492585278 9020068072 11518973205 932760554F 9586696097 9961995244 11166740981 11378142289F 11368440756F 15177143911 15877224330 -o docs/source/ -c 'Bavarian alps traverse'
          cd docs
          make clean
          make html
          cd ..
          ls docs/build/html/index.html
